apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Platform infrastructure — Argo CD, Prometheus, monitoring config

  sourceRepos:
    - https://github.com/akalyan3/gitops-argocd.git
    - https://argoproj.github.io/argo-helm
    - https://prometheus-community.github.io/helm-charts

  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: monitoring

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  roles:
    - name: read-only
      description: Read-only access for auditing
      policies:
        - p, proj:platform:read-only, applications, get, platform/*, allow
      groups:
        - platform-readers
